name: Run app.py with cron job

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install FFmpeg & ImageMagick
        run: |
          sudo apt update
          sudo apt install -y ffmpeg imagemagick

      - name: Verify Installation
        run: |
          python -c "import moviepy.editor as mp; print('MoviePy is working!')"
          ffmpeg -version
          convert -version  # Check ImageMagick

      - name: Run the script
        run: python app.py
