name: Initiate Pipelines

on:
  schedule:
    - cron: "30 18 * * *"  # Runs at 12:00 AM IST (IST = UTC+5:30)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install --force-reinstall moviepy
          pip install -r requirements.txt

      - name: Verify Installed Packages
        run: pip list  # Debugging step to check installed packages

      - name: Test MoviePy Import
        run: python -c "import moviepy.editor"  # Ensures MoviePy is installed properly

      - name: Set up ImageMagick
        run: |
          echo "Setting ImageMagick policy..."
          sudo sed -i 's/none/read|write/g' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/none/read|write/g' /etc/ImageMagick-7/policy.xml || true

      - name: Run the Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SPEECHIFY_API_KEY: ${{ secrets.SPEECHIFY_API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          MIN_IMAGES: ${{ secrets.MIN_IMAGES }}

          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}

          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_PROJECT_ID: ${{ secrets.YT_PROJECT_ID }}
          YT_AUTH_URI: ${{ secrets.YT_AUTH_URI }}
          YT_TOKEN_URI: ${{ secrets.YT_TOKEN_URI }}
          YT_REDIRECT_URI: ${{ secrets.YT_REDIRECT_URI }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}

        run: python app.py
